# Use root/example as user/password credentials 
version: '3.1' 

services:

  db:
    container_name: db
    image: mysql:5.7.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - $PWD/mysql_data:/var/lib/mysql
    
  db-adminer:
    container_name: db-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  metabase:
    image: metabase/metabase
    restart: always
    environment:
      MB_DB_FILE: /metabase.db
    ports:
      - 3000:3000
    volumes:
      - $PWD/metabase_data:/metabase.db

  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    ports:
      - 8000:8000

  dynamodb-admin: 
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin 
    ports: 
      - 8001:8001 
    environment: 
      - AWS_REGION=eu-west-1 
      - AWS_ACCESS_KEY_ID=local 
      - AWS_SECRET_ACCESS_KEY=local 
      - DYNAMO_ENDPOINT=http://dynamodb:8000

  jupyter-tutorial:
    image: jupyter/base-notebook
    container_name: jupyter.local
    user: root
    environment:
      - GRANT_SUDO=yes 
    ports:
      - "8888:8888"
      - "5000:5000"
    volumes:
      - ./tutorial:/home/jovyan/work/
    command: start-notebook.sh --NotebookApp.token=''
